abstract: Term::Screen for Net::Partty
author: Kazuhiro Osawa <ko@yappo.ne.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Net-Partty-Screen
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Term::ReadKey: 0
requires: 
  Net::Partty: 0
  Term::Cap: 0
  Term::Screen: 0
version: 0.01
